name: Task Flow Summary

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  task_flow:
    name: Task Flow
    runs-on: ubuntu-latest

    outputs:
      task_1_completed: ${{ steps.task_1.result }}
      task_2_completed: ${{ steps.task_2.result }}
      task_3_completed: ${{ steps.task_3.result }}
      task_4_completed: ${{ steps.task_4.result }}

    steps:
      - name: Task 1
        id: task_1
        run: echo "Executing Task 1"
      
      - name: Task 2
        id: task_2
        run: echo "Executing Task 2"
      
      - name: Task 3
        id: task_3
        run: echo "Executing Task 3"
      
      - name: Task 4
        id: task_4
        run: echo "Executing Task 4"

      - name: Summarize Task Flow
        if: always()
        run: |
          echo "Summary of Task Flow:"
          echo "Task 1: ${{ needs.task_flow.outputs.task_1_completed }}"
          echo "Task 2: ${{ needs.task_flow.outputs.task_2_completed }}"
          echo "Task 3: ${{ needs.task_flow.outputs.task_3_completed }}"
          echo "Task 4: ${{ needs.task_flow.outputs.task_4_completed }}"

# Display job-level summary in workflow run
