name: Summary
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        run: |
          echo "Configuring AWS credentials..."

          # Use aws-actions/configure-aws-credentials@v4 to configure AWS credentials
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1
          echo "AWS credentials configured successfully."

      # Step 2: Create CodeDeploy Deployment
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          echo "Creating CodeDeploy deployment..."

          # Execute AWS CLI command to create deployment
          DEPLOYMENT_ID=$(aws deploy create-deployment \
                          --application-name FlaskApp \
                          --deployment-group-name FlaskGroup \
                          --deployment-config-name CodeDeployDefault.OneAtATime \
                          --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
                          --query "deploymentId" --output text)
          echo "Deployment created with ID: ${DEPLOYMENT_ID}"
          echo "::set-output name=deploymentId::${DEPLOYMENT_ID}"
          
        # Annotate step with details for summary view
        if: always()
        continue-on-error: true
        env:
          DEPLOYMENT_ID: ${{ steps.deploy.outputs.deploymentId }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.actions.createCheckRun({
              name: 'Create CodeDeploy Deployment',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Deployment Created Successfully',
                summary: 'Deployment ID: ' + process.env.DEPLOYMENT_ID,
              }
            });
